// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADGx5Xv99KaW0QqtJFhXez_gx_2Ne1XkM',
    appId: '1:652748650556:web:319970bf99a9f9249fab39',
    messagingSenderId: '652748650556',
    projectId: 'x-pathfinder',
    authDomain: 'x-pathfinder.firebaseapp.com',
    storageBucket: 'x-pathfinder.appspot.com',
    measurementId: 'G-MZ7LNRL2GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9S7I53mOLP4UrQrSIQvO16H66SyhTwSA',
    appId: '1:652748650556:android:6351c74eaf91cf989fab39',
    messagingSenderId: '652748650556',
    projectId: 'x-pathfinder',
    storageBucket: 'x-pathfinder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG-lVvU9RcZ9qZFGxGVB7we8qL4WenG30',
    appId: '1:652748650556:ios:b02a4c5ddb8f4ac89fab39',
    messagingSenderId: '652748650556',
    projectId: 'x-pathfinder',
    storageBucket: 'x-pathfinder.appspot.com',
    iosClientId: '652748650556-eonurmn3s8kqraclfmj9qjdjpfl0u0g6.apps.googleusercontent.com',
    iosBundleId: 'com.thinkalt.babyClaridges',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG-lVvU9RcZ9qZFGxGVB7we8qL4WenG30',
    appId: '1:652748650556:ios:b02a4c5ddb8f4ac89fab39',
    messagingSenderId: '652748650556',
    projectId: 'x-pathfinder',
    storageBucket: 'x-pathfinder.appspot.com',
    iosClientId: '652748650556-eonurmn3s8kqraclfmj9qjdjpfl0u0g6.apps.googleusercontent.com',
    iosBundleId: 'com.thinkalt.babyClaridges',
  );
}
